services:
  - type: web
    name: user-behavior-analytics-api
    env: node
    buildCommand: npm install && tsc && node dist/utils/initDB.js
    startCommand: npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: user-behavior-analytics-db
          property: connectionString
      - key: CORS_ORIGIN
        value: "https://whwnddml.github.io,https://*.brandiup.com"
      - key: LOG_LEVEL
        value: "info"

databases:
  - name: user-behavior-analytics-db
    databaseName: uba
    ipAllowList: []  # 모든 IP 허용 