services:
  - type: web
    name: user-behavior-analytics-api
    env: node
    buildCommand: npm install && tsc && node dist/utils/initDB.js
    startCommand: npm start
    healthCheckPath: /api/analytics/health
    healthCheckTimeout: 60
    autoDeploy: true
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: uba_zfqs
          property: connectionString
      - key: CORS_ORIGIN
        value: "https://whwnddml.github.io,https://skybab.brandiup.com,https://brandiup.com,https://www.brandiup.com"
      - key: LOG_LEVEL
        value: "info"
    disk:
      name: logs
      mountPath: /opt/render/project/src/backend/logs
      sizeGB: 1

databases:
  - name: uba_zfqs
    databaseName: uba_zfqs
    user: brandiup
    plan: free
    ipAllowList:
      - source: 0.0.0.0/0
        description: everywhere 