name: Deploy Backend to Render

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'
      - '.github/workflows/deploy_backend.yml'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # Render는 자동으로 main 브랜치의 변경사항을 감지하여 배포하므로,
      # 여기서는 단순히 테스트와 빌드 검증만 수행합니다.
      - name: Install Dependencies
        run: |
          cd backend
          npm ci

      - name: Run Tests
        run: |
          cd backend
          npm run test

      - name: Build Check
        run: |
          cd backend
          npm run build 